CREATE TABLE STUDENT (
  STUDENT_ID INT PRIMARY KEY,
  STUDENT_MARK  VARCHAR(255),
  STUDENT_NAME  VARCHAR(255)
);

INSERT INTO STUDENT(STUDENT_ID,STUDENT_MARK,STUDENT_NAME) 
VALUES (1, "244", "AFFAN");


select * FROM STUDENT;

